joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

shoulder_pan_joint_effort:
  type: effort_controllers/JointEffortController
  joint: shoulder_pan_joint
  pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

shoulder_lift_joint_effort:
  type: effort_controllers/JointEffortController
  joint: shoulder_lift_joint
  pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

elbow_joint_effort:
  type: effort_controllers/JointEffortController
  joint: elbow_joint
  pid: {p: 80.0, i: 0.01, d: 8.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

wrist_1_joint_effort:
  type: effort_controllers/JointEffortController
  joint: wrist_1_joint
  pid: {p: 40.0, i: 0.01, d: 4.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

wrist_2_joint_effort:
  type: effort_controllers/JointEffortController
  joint: wrist_2_joint
  pid: {p: 30.0, i: 0.01, d: 3.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

wrist_3_joint_effort:
  type: effort_controllers/JointEffortController
  joint: wrist_3_joint
  pid: {p: 20.0, i: 0.01, d: 2.0, i_clamp_min: -1.0, i_clamp_max: 1.0}


